#define SETUP 1

#if SETUP == 1
#define DEVICE_NAME_HR "HR6 0031452"
#define DEVICE_NAME_HR2 "HR8 30743"
#define DEVICE_NAME_POWER "KICKR CORE 28DF"
#define DEVICE_NAME_SPEED "XXX"
#define DEVICE_NAME_GPS "XXX"
#endif
#if SETUP == 2
#define DEVICE_NAME_HR "HR6 0031452"
#define DEVICE_NAME_HR2 "HR8 30743"
#define DEVICE_NAME_POWER "ASSIOMA13805L"
#define DEVICE_NAME_SPEED "CS8L-S 45539"
#define DEVICE_NAME_GPS "XXX"
#endif

#define FEATURE_SCREEN_ENABLED
#define FEATURE_GPS_ENABLED
#define FEATURE_HR_ENABLED
#define FEATURE_POWER_ENABLED
// #define FEATURE_SPEED_ENABLED

#define BOARD_LILY_WRIST 1
#define BOARD_LILY_154 2
#define BOARD_WAVESHARE 3
#define BOARD BOARD_LILY_WRIST