#include "esp_log.h"

#define DEVELOPMENT
#define SETUP 2

#if SETUP == 1
#define DEVICE_NAME_HR "HR6 0031452"
#define DEVICE_NAME_HR2 "HR8 30743"
#define DEVICE_NAME_POWER "KICKR CORE 28DF" // f9:4a:e9:9a:67:4d
#define DEVICE_NAME_SPEED "XXX"
#define DEVICE_NAME_AIRSPEED "VELOMETA_AIRSPEED"
#define DEVICE_NAME_GPS "XXX"
#endif
#if SETUP == 2
#define DEVICE_NAME_HR "HR6 0031452"
#define DEVICE_NAME_HR2 "HR8 30743"
#define DEVICE_NAME_POWER "ASSIOMA13805L"
#define DEVICE_NAME_SPEED "CS8L-S 45539"
#define DEVICE_NAME_AIRSPEED "VELOMETA_AIRSPEED"
#define DEVICE_NAME_GPS "XXX"
#endif

#define FEATURE_SCREEN_ENABLED
#define FEATURE_GPS_ENABLED
#define FEATURE_HR_ENABLED
#define FEATURE_POWER_ENABLED
// #define FEATURE_SPEED_ENABLED

#define BOARD_LILY_WRIST 1
#define BOARD_LILY_154 2
#define BOARD_WAVESHARE 3
#define WTSC01_PLUS 4
#define BOARD BOARD_LILY_154

#define MSG_NEW_SPEED 1
#define MSG_NEW_POWER 2
#define MSG_NEW_HR 3
#define MSG_NEW_HEADING 4
#define MSG_NEW_GPS 5
#define MSG_NEW_HR_W 6

#if BOARD == WTSC01_PLUS
#define VM_I2C_0_SDA 10
#define VM_I2C_0_SCL 11

#define VM_I2C_1_SDA 12
#define VM_I2C_1_SCL 13

#define VM_I2C_2_SDA 14
#define VM_I2C_2_SCL 21
#elif BOARD == BOARD_LILY_154
#define VM_I2C_0_SDA 10
#define VM_I2C_0_SCL 11

#define VM_I2C_1_SDA 20
#define VM_I2C_1_SCL 21

#define VM_I2C_2_SDA 22
#define VM_I2C_2_SCL 23
#endif

#if BOARD == BOARD_LILY_WRIST
#define P_CS 15
#define P_DC 2
#define P_RST 17
#define P_BUSY 16
#define EPD_SCK_PIN 14
#define EPD_MOSI_PIN 13
#elif BOARD == BOARD_LILY_154
#define P_CS 5
#define P_DC 17
#define P_RST 16
#define P_BUSY 4
#define EPD_SCK_PIN 18
#define EPD_MOSI_PIN 23
#elif BOARD == BOARD_WAVESHARE
#define EPD_CS_PIN 15
#define EPD_RST_PIN 26
#define EPD_DC_PIN 27
#define EPD_BUSY_PIN 25
#endif

#define POSITION_SENSOR_ADDRESS 0x29
#define POSITION_SENSOR_SDA VM_I2C_0_SDA
#define POSITION_SENSOR_SCL VM_I2C_0_SCL

#define ENVIRONMENTAL_SENSOR_ADDRESS 0x77
#define ENVIRONMENTAL_SENSOR_SDA VM_I2C_0_SDA
#define ENVIRONMENTAL_SENSOR_SCL VM_I2C_0_SCL

#define IMU_SENSOR_ADDRESS 0x77
#define IMU_SENSOR_SDA VM_I2C_0_SDA
#define IMU_SENSOR_SCL VM_I2C_0_SCL

#define AIR_PRESSURE_SENSOR_ADDRESS 0x6D
#define AIR_PRESSURE_SENSOR_SDA VM_I2C_0_SDA
#define AIR_PRESSURE_SENSOR_SCL VM_I2C_0_SCL
