#define SETUP 2

#if SETUP == 1
#define DEVICE_NAME_HR "HR6 0031452"
#define DEVICE_NAME_POWER "KICKR CORE 28DF"
#define DEVICE_NAME_SPEED "XXX"
#define DEVICE_NAME_GPS "XXX"
#endif
#if SETUP == 2
#define DEVICE_NAME_HR "HR6 0031452"
#define DEVICE_NAME_POWER "ASSIOMA13805L"
#define DEVICE_NAME_SPEED "CS8L-S 45539"
#define DEVICE_NAME_GPS "XXX"
#endif